#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

/**
 * php -d phar.readonly=0 genphar pack -o swagphp.phar
 */
$input = new \Inhere\Console\IO\Input();
$output = new \Inhere\Console\IO\Output();

$ctrl = new \Inhere\Console\BuiltIn\PharController($input, $output);
$ctrl->setExecutionAlone();

// config
$ctrl->setCompilerConfiger(function (\Inhere\Console\Components\PharCompiler $compiler) {
    $compiler
        // ->stripComments(false)
        ->setShebang(true)
        ->addExclude([
            'doc',
            'docs',
            'demo',
            'demos',
            'node_modules',
            'test',
            'tests',
            'Tests',
            'example',
            'examples',
            'tmp',
        ])
        ->notName([

        ])
        ->addFile([
            'LICENSE',
            'composer.json',
            'README.md'
        ])
        ->setCliIndex('bin/swagphp')
        // ->setWebIndex('web/index.php')
        // ->setVersionFile('config/config.php')
    ;

    // Command 下的命令类不去除注释，注释上是命令帮助信息
    $compiler->setStripFilter(function ($file) {
        /** @var \SplFileInfo $file */
        $name = $file->getFilename();

        return false === strpos($name, 'Command.php');
    });
});

try {
    exit($ctrl->run($input->getCommand()));
} catch (\Exception $e) {
    $message = \Toolkit\Cli\Color::apply('error', $e->getMessage());

    echo sprintf("%s\nFile %s:%d\nTrace:\n%s\n",
        $message, $e->getFile(), $e->getLine(), $e->getTraceAsString()
    );
}